name: divyangsarthi_app
description: Divyangsarthi app scaffold
publish_to: "none"
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  dio: ^5.0.0
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^8.0.0
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
flutter:
  assets:
    - assets/images/logo.png
